/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xy.coordinates;

/**
 *
 * @author Lenovo
 */

import javax.swing.*;
import java.awt.*;
import java.awt.Graphics;

public class MainFrame extends javax.swing.JFrame {

DrawPanel drawPanel = new DrawPanel();  

    public static int point_count=0;
    String txt="";
    public static int[][]input_points = new int[100][2];
    
    public static int[][]draw_points;
    

    
    public MainFrame() {
        initComponents();
        
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        y_txt = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        x_txt = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        draw = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 750));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(62, 54, 54));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/close_window_20px.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 30, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 238, 163));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimum_value_20px.png"))); // NOI18N
        jLabel3.setText("XY COORDINATE SYSTEM");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/help_20px.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 30, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 30));

        mainPanel.setBackground(new java.awt.Color(89, 105, 125));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(180, 205, 147));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        y_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        y_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        y_txt.setText("y-coordinate");
        y_txt.setBorder(null);
        y_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                y_txtMouseClicked(evt);
            }
        });
        jPanel4.add(y_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 58, 94, 40));

        submit.setBackground(new java.awt.Color(89, 105, 125));
        submit.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(180, 205, 147));
        submit.setText("SUBMIT");
        submit.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        submit.setFocusable(false);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel4.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 116, 100, 40));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Please Enter Your Point");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 20));

        x_txt.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        x_txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        x_txt.setText("x-coordinate");
        x_txt.setBorder(null);
        x_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                x_txtMouseClicked(evt);
            }
        });
        jPanel4.add(x_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 58, 94, 40));

        mainPanel.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 170));

        jPanel5.setBackground(new java.awt.Color(128, 128, 128));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("POINTS");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 20));

        clear.setBackground(new java.awt.Color(89, 105, 125));
        clear.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        clear.setForeground(new java.awt.Color(180, 205, 147));
        clear.setText("CLEAR");
        clear.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        clear.setFocusable(false);
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel5.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 100, 40));

        ta.setColumns(20);
        ta.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        ta.setLineWrap(true);
        ta.setRows(5);
        ta.setWrapStyleWord(true);
        jScrollPane1.setViewportView(ta);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, 370));

        draw.setBackground(new java.awt.Color(89, 105, 125));
        draw.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        draw.setForeground(new java.awt.Color(180, 205, 147));
        draw.setText("DRAW");
        draw.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        draw.setFocusable(false);
        draw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drawActionPerformed(evt);
            }
        });
        jPanel5.add(draw, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 100, 40));

        mainPanel.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 300, 550));

        mainPanel.add(drawPanel,new org.netbeans.lib.awtextra.AbsoluteConstraints(310,10,700,700));

        jPanel1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1020, 720));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked

        System.exit(0);
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed

       
        input_points[point_count][0] = Integer.parseInt(x_txt.getText());
        input_points[point_count][1] = Integer.parseInt(y_txt.getText());
        
        txt += "("+input_points[point_count][0]+","+input_points[point_count][1]+")\t";
        
        ta.setText(txt);

        x_txt.setText("");
        y_txt.setText("");
        
       point_count++;
       
  //     System.out.println(" "+point_count);
       
    }//GEN-LAST:event_submitActionPerformed

    private void x_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_x_txtMouseClicked

        x_txt.setText("");
        
    }//GEN-LAST:event_x_txtMouseClicked

    private void y_txtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_y_txtMouseClicked

        y_txt.setText("");
        
    }//GEN-LAST:event_y_txtMouseClicked

    private void drawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drawActionPerformed


    draw_points = new int[point_count][2];
    
    for(int i=0;i<draw_points.length;i++) {
        
        draw_points[i][0] = input_points[i][0];
        draw_points[i][1] = input_points[i][1];
        
//        System.out.println("("+draw_points[i][0]+","+draw_points[i][1]+")");

    }

    

mainPanel.repaint();
    
        DrawPanel.changePoints(draw_points, draw_points.length);
        
    mainPanel.add(drawPanel,new org.netbeans.lib.awtextra.AbsoluteConstraints(310,10,700,700));
    

    }//GEN-LAST:event_drawActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed

        x_txt.setText("x-coordinate");
        y_txt.setText("y-coordinate");
        
        txt="";
        ta.setText("");
        
        point_count=0;
        
        input_points = new int[100][2];

        draw_points = new int[point_count][2];
    
    for(int i=0;i<draw_points.length;i++) {
        
        draw_points[i][0] = input_points[i][0];
        draw_points[i][1] = input_points[i][1];
        
//        System.out.println("("+draw_points[i][0]+","+draw_points[i][1]+")");

    }

    

mainPanel.repaint();

        DrawPanel.changePoints(draw_points,draw_points.length);
        mainPanel.add(drawPanel,new org.netbeans.lib.awtextra.AbsoluteConstraints(310,10,700,700));

    }//GEN-LAST:event_clearActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked

        Help help = new Help();
        help.setVisible(true);
        
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton draw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton submit;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField x_txt;
    private javax.swing.JTextField y_txt;
    // End of variables declaration//GEN-END:variables
}
